<?php

declare(strict_types=1);

require dirname(__DIR__) . '/app/bootstrap.php';

use App\Support\Router;
use App\Controllers\HomeController;
use App\Controllers\ProductController;
use App\Controllers\CheckoutController;
use App\Controllers\OrderController;
use App\Controllers\StatusController;
use App\Controllers\WebhookController;
use App\Controllers\PageController;
use App\Controllers\AdminAuthController;
use App\Controllers\AdminDashboardController;
use App\Controllers\AdminCategoryController;
use App\Controllers\AdminProductController;
use App\Controllers\AdminOrderController;
use App\Controllers\AdminLogController;
use App\Controllers\AdminSettingsController;
use App\Controllers\UserAuthController;
use App\Controllers\AdminUserController;
use App\Controllers\UserDashboardController;
use App\Controllers\UserMarketController;
use App\Controllers\ModeratorController;
use App\Controllers\AdminInviteKeyController;
use App\Controllers\DonationController;
use App\Controllers\Api\Desktop\AuthController as DesktopAuthController;
use App\Controllers\Api\Desktop\CategoriesController as DesktopCategoriesController;
use App\Controllers\Api\Desktop\DashboardController as DesktopDashboardController;
use App\Controllers\Api\Desktop\InfoController as DesktopInfoController;
use App\Controllers\Api\Desktop\InvitesController as DesktopInvitesController;
use App\Controllers\Api\Desktop\LogsController as DesktopLogsController;
use App\Controllers\Api\Desktop\OrdersController as DesktopOrdersController;
use App\Controllers\Api\Desktop\ProductsController as DesktopProductsController;
use App\Controllers\Api\Desktop\UsersController as DesktopUsersController;

$router = new Router();
$router->get('/api/desktop', [DesktopInfoController::class, 'index']);
$router->post('/api/desktop/auth/login', [DesktopAuthController::class, 'login']);
$router->get('/api/desktop/auth/me', [DesktopAuthController::class, 'me']);
$router->post('/api/desktop/auth/logout', [DesktopAuthController::class, 'logout']);
$router->get('/api/desktop/dashboard', [DesktopDashboardController::class, 'index']);
$router->get('/api/desktop/orders', [DesktopOrdersController::class, 'index']);
$router->get('/api/desktop/orders/{id}', [DesktopOrdersController::class, 'show']);
$router->post('/api/desktop/orders/{id}/status', [DesktopOrdersController::class, 'updateStatus']);
$router->post('/api/desktop/orders/{id}/note', [DesktopOrdersController::class, 'addNote']);
$router->get('/api/desktop/users', [DesktopUsersController::class, 'index']);
$router->get('/api/desktop/users/{id}', [DesktopUsersController::class, 'show']);
$router->post('/api/desktop/users/{id}/ban', [DesktopUsersController::class, 'ban']);
$router->post('/api/desktop/users/{id}/unban', [DesktopUsersController::class, 'unban']);
$router->post('/api/desktop/users/{id}/coins', [DesktopUsersController::class, 'adjustCoins']);
$router->get('/api/desktop/categories', [DesktopCategoriesController::class, 'index']);
$router->post('/api/desktop/categories', [DesktopCategoriesController::class, 'create']);
$router->get('/api/desktop/products', [DesktopProductsController::class, 'index']);
$router->post('/api/desktop/products', [DesktopProductsController::class, 'create']);
$router->post('/api/desktop/products/{id}', [DesktopProductsController::class, 'update']);
$router->post('/api/desktop/products/{id}/delete', [DesktopProductsController::class, 'delete']);
$router->get('/api/desktop/logs', [DesktopLogsController::class, 'index']);
$router->get('/api/desktop/invites', [DesktopInvitesController::class, 'index']);
$router->post('/api/desktop/invites', [DesktopInvitesController::class, 'create']);
$router->post('/api/desktop/invites/{id}/delete', [DesktopInvitesController::class, 'delete']);

$router->get('/', [HomeController::class, 'index']);
$router->get('/produto/{slug}', [ProductController::class, 'show']);
$router->post('/checkout/create', [CheckoutController::class, 'create']);
$router->get('/pedido', [OrderController::class, 'lookup']);
$router->post('/pedido', [OrderController::class, 'lookupSubmit']);
$router->get('/pedido/{publicId}', [OrderController::class, 'show']);
$router->post('/pedido/{publicId}/contato', [OrderController::class, 'updateContact']);
$router->get('/success', [StatusController::class, 'success']);
$router->get('/pending', [StatusController::class, 'pending']);
$router->get('/failure', [StatusController::class, 'failure']);
$router->get('/termos', [PageController::class, 'terms']);
$router->get('/produtos', [PageController::class, 'products']);
$router->get('/servicos', [PageController::class, 'services']);
$router->post('/servicos', [PageController::class, 'servicesSubmit']);
$router->get('/doacoes', [PageController::class, 'donations']);
$router->post('/doacoes', [DonationController::class, 'create']);
$router->get('/login', [UserAuthController::class, 'showLogin']);
$router->post('/login', [UserAuthController::class, 'login']);
$router->get('/register', [UserAuthController::class, 'showRegister']);
$router->post('/register', [UserAuthController::class, 'register']);
$router->get('/verify-email/pending', [UserAuthController::class, 'showVerificationPending']);
$router->post('/verify-email/resend', [UserAuthController::class, 'resendVerification']);
$router->get('/verify-email/confirm', [UserAuthController::class, 'verifyEmail']);
$router->post('/logout', [UserAuthController::class, 'logout']);
$router->get('/usuario', [UserDashboardController::class, 'index']);
$router->get('/usuario/inventario', [UserDashboardController::class, 'inventory']);
$router->post('/usuario/inventario/desbloquear', [UserDashboardController::class, 'unlockInventoryItem']);
$router->get('/usuario/mercado', [UserMarketController::class, 'index']);
$router->get('/usuario/mercado/comprar', [UserMarketController::class, 'browse']);
$router->get('/usuario/mercado/historico', [UserMarketController::class, 'history']);
$router->post('/usuario/mercado/coins/comprar', [UserMarketController::class, 'buyCoins']);
$router->post('/usuario/mercado/ofertas/criar', [UserMarketController::class, 'createListing']);
$router->post('/usuario/mercado/ofertas/comprar', [UserMarketController::class, 'buyListing']);
$router->post('/usuario/mercado/ofertas/cancelar', [UserMarketController::class, 'cancelListing']);
$router->get('/moderadores/{slug}', [ModeratorController::class, 'show']);
$router->post('/webhook/mercadopago', [WebhookController::class, 'handle']);

$router->get('/admin/login', [AdminAuthController::class, 'showLogin']);
$router->post('/admin/login', [AdminAuthController::class, 'login']);
$router->get('/admin/2fa/setup', [AdminAuthController::class, 'showTwoFactorSetup']);
$router->post('/admin/2fa/setup', [AdminAuthController::class, 'setupTwoFactor']);
$router->get('/admin/2fa/verify', [AdminAuthController::class, 'showTwoFactorVerify']);
$router->post('/admin/2fa/verify', [AdminAuthController::class, 'verifyTwoFactor']);
$router->get('/admin/setup', [AdminAuthController::class, 'showSetup']);
$router->post('/admin/setup', [AdminAuthController::class, 'setup']);
$router->get('/admin/register', [AdminAuthController::class, 'showRegister']);
$router->post('/admin/register', [AdminAuthController::class, 'register']);
$router->post('/admin/logout', [AdminAuthController::class, 'logout']);
$router->match(['GET','POST'], '/admin/dashboard', [AdminDashboardController::class, 'index']);
$router->match(['GET','POST'], '/admin/categories', [AdminCategoryController::class, 'index']);
$router->match(['GET','POST'], '/admin/products', [AdminProductController::class, 'index']);
$router->match(['GET','POST'], '/admin/orders', [AdminOrderController::class, 'index']);
$router->match(['GET','POST'], '/admin/settings', [AdminSettingsController::class, 'index']);
$router->match(['GET','POST'], '/admin/users', [AdminUserController::class, 'index']);
$router->match(['GET','POST'], '/admin/invites', [AdminInviteKeyController::class, 'index']);
$router->get('/admin/logs', [AdminLogController::class, 'index']);

$uri = parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH) ?? '/';
$router->dispatch($_SERVER['REQUEST_METHOD'] ?? 'GET', $uri);
